version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - frontend

#  server:
#    build:
#      context: ./server
#      dockerfile: Dockerfile
#    ports:
#      - "5000:5000"
#    volumes:
#      - ./server:/app
#      - /app/node_modules
#    depends_on:
#      - postgres
#    networks:
#      - backend
#
#  postgres:
#    image: postgres:13
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: hiking_guardian
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#    networks:
#      - backend
#
#volumes:
#  postgres-data:
#
networks:
  frontend:
#  backend:
